Fixed up sinktools, removed some old scripts.

diff --git a/sinktools b/sinktools
--- a/sinktools
+++ b/sinktools
@@ -1,143 +1,217 @@
 #!/bin/bash
 
 
-args=("$@")
-argsLength=${#args[@]}
-
-
-getVolume=$(pactl get-sink-volume $(pactl get-default-sink))
+programName="sinktools"
 currentSink=$(pactl get-default-sink)
-sinksString=$(pactl list sinks | grep Name:)
-sinksString=$(sed 's/Name: //' <<< $sinksString)
-sinksArray=($sinksString)
+maxVol="100"
+minVol="0"
+volIncValue="5"
 
 
-get-volume-percent () {
+usage () {
 
-    rmBeg=$(sed 's/Volume: front-left: [0-9]* \/[ \t]*//' <<< $getVolume)
+    echo "usage: $programName {-h|-n|-p|-l|-r|-i|-v|-m} (-h for help)"
+}
+
+
+help () {
+
+    echo ""
+    usage
+    echo ""
+    echo "-n:"
+    echo "      Next audio sink."
+    echo "-p:"
+    echo "      Previous audio sink."
+    echo "-l:"
+    echo "      Print a simple list of all available audio sinks."
+    echo "-r:"
+    echo "      List all available audio sinks in rofi. They are selectable from the list."
+    echo "-i:"
+    echo "      Print info about the current (default) audio sink."
+    echo "-v:"
+    echo "      Volume settings. This option requires parameters:"
+    echo "      {up | down | +/-[0-100] | [0-100]}"
+    echo "-m:"
+    echo "      Mute/unmute the current sink. Optional paramaters:"
+    echo "      [0 | 1]"
+}
+
+
+get-current-volume () {
+
+    volString=$(pactl get-sink-volume $(pactl get-default-sink))
+    rmBeg=$(sed 's/Volume: front-left: [0-9]* \/[ \t]*//' <<< $volString)
     percent=$(sed 's/ .*//' <<< $rmBeg)
-    echo $percent
+    numberOnly=$(echo $percent | sed 's/%//')
+    echo $numberOnly
+}
+
+
+print-volume-percent () {
+    
+    echo "$(get-current-volume)%"
+}
+
+
+print-info () {
+    
+    echo "Default sink: $currentSink"
+    echo "Volume: $(print-volume-percent)"
 }
 
 
 set-volume () {
 
-    upString="+5%"
-    downString="-5%"
+    currentVol=$(get-current-volume)
 
-    setVolume="pactl set-sink-volume"
-    
-    if [[ $argsLength -lt 2 ]]
-    then
-        echo "Usage: sinktools -set-volume -up|-down"
+    if [[ $OPTARG == "up" ]]
+    then # default increment up
+        newVol=$(validate-volume $(( $currentVol + $volIncValue )))
+    elif [[ $OPTARG == "down" ]]
+    then # default increment down
+        newVol=$(validate-volume $(( $currentVol - $volIncValue )))
+    elif [[ "$OPTARG" =~ ^[+][0-9]+$ || "$OPTARG" =~ ^[-][0-9]+$ ]]
+    then # user defined value of increment
+        newVol=$(validate-volume $(( $currentVol + $OPTARG )))
+    elif [[ "$OPTARG" =~ ^[0-9]+$ ]]
+    then # user specified value - specific value
+        newVol=$(validate-volume $OPTARG)
+    else
+        echo "Invalid argument: $OPTARG ($programName -h for help)"
         exit 1
     fi
-    if [[ ${args[1]} == "-up" ]]
+
+    pactl set-sink-volume $currentSink "$newVol%"
+    print-volume-percent
+}
+
+
+validate-volume () {
+
+    if [[ $1 -gt $maxVol ]]
     then
-	if [[ $(check-if-max-volume) == 1 ]] 
-	then
-	    $setVolume $(pactl get-default-sink) 100%
-        else
-	    $setVolume $(pactl get-default-sink) $upString
-	fi
-    elif [[ ${args[1]} == "-down" ]]
+        echo $maxVol
+    elif [[ $1 -lt $minVol ]]
     then
-        $setVolume $(pactl get-default-sink) $downString
+        echo $minVol
     else
-        echo "Usage: sinktools -set-volume -up|-down"
-        exit 1
+        echo $1
     fi
 }
 
 
-check-if-max-volume () {
+mute () {
 
-    vol=$(get-volume-percent)
-    volInt=$(sed 's/%//' <<< $vol)
-    nextVol=$((volInt + 5))
-
-    if [[ $nextVol -ge 100 ]]
+    isMuted=$(pactl get-sink-mute $currentSink)
+    echo $#
+    
+    if [[ $# == 0 ]]
     then
-	echo 1
+
+        if [[  $isMuted == "Mute: no" ]]; then
+            muteState=1
+        else
+            muteState=0
+        fi
+
     else
-	echo 0
+        if [[ $1 == 0 || $1 == 1 ]]; then
+            muteState=$1
+        else
+            echo "Invalid argument: $1. $programName -m takes optional paramater of 0 or 1"
+            exit 1
+        fi
     fi
+
+    pactl set-sink-mute $currentSink $muteState
 }
 
 
 change-sink () {
 
-    if [[ $argsLength -gt 1 ]]
-    then
-        if [[ ${args[1]} == "-m" ]]
-        then
-            change-sink-menu
-        else
-            echo "Usage: sinktools -change-sink (-m)"
-            exit 1
-        fi
-    else
-        next-sink
-    fi
-}
+    sinkArray=($(list-sinks))
+    length=${#sinkArray[@]}
+    index=0
+    newIndex=0
 
-
-next-sink () {
-
-    length=${#sinksArray[@]}
-
-    i=0
-    while [[ $i < $length ]]
+    while [[ $index < $length ]]
     do
-        if [[ $currentSink == ${sinksArray[$i]} ]]
+        if [[ $currentSink == ${sinkArray[$index]} ]]
         then
-            if [[ $i == $(( $length - 1 )) ]]
-            then
-                pactl set-default-sink ${sinksArray[0]}
-            else
-                pactl set-default-sink ${sinksArray[$i + 1]}
-            fi
-        pactl get-default-sink
+            newIndex=$(( $index + $1 ))
+            break
         fi
-        i=$(( $i + 1 ))
+        index=$(( $index + 1 ))
     done
+
+
+    if [[ $newIndex > $(( $length - 1 )) ]]
+    then
+        pactl set-default-sink ${sinkArray[0]}
+    elif [[ $newIndex < 0 ]]
+    then
+        pactl set-default-sink ${sinkArray[$length - 1]}
+    else
+        pactl set-default-sink ${sinkArray[$newIndex]}
+    fi
+    pactl get-default-sink
 }
 
-change-sink-menu () {
 
-    pactl set-default-sink $(pactl list sinks | 
-        grep Name: | 
-        sed 's/Name: //' | 
-        sed 's/^[ \t]*//' | 
-        rofi -dmenu -window-title 'Audio Sink')
-
-        pactl get-default-sink
+list-sinks () {
+    
+    pactl list sinks |
+        grep Name: |
+        sed 's/Name: //' |
+        sed 's/^[ \t]*//'
 }
 
 
-# check if user gave arguments
-if [[ $argsLength -lt 1 ]]
-then
-    echo "sinktools needs arguments"
-    exit 1
-fi
+list-sinks-in-rofi () {
+    
+    title="Audio Sinks"
 
-if [[ ${args[0]} == "-change-sink" ]]
-then
-    change-sink
-    exit 0
-fi
+    pactl set-default-sink $(
+        list-sinks |
+        rofi -dmenu -window-title $title
+    )
+}
 
-if [[ ${args[0]} == "-get-volume" ]]
-then
-    get-volume-percent
-    exit 0
-fi
 
-if [[ ${args[0]} == "-set-volume" ]]
-then
-    set-volume
-    exit 0
-fi
+while getopts ":hpnlriv:m" option; do
+    case $option in
+        h)  # Help
+            help
+            exit;;
+        i)  # Get current sink info
+            print-info
+            exit;;
+        n)  # Next sink
+            change-sink 1
+            exit;;
+        p)  # Previous sink
+            change-sink -1
+            exit;;
+        l)  # List sinks
+            list-sinks
+            exit;;
+        r)  # Rofi
+            list-sinks-in-rofi
+            exit;;
+        v)  # Set volume - needs argument
+            set-volume
+            exit;;
+        m)  # Mute/unmute current sink
+            mute $2
+            exit;;
+        :)  # Error message for options that require argument
+            echo "$programName -${OPTARG} requires an argument"
+            exit 1;;
+        \?) # Invalid option
+            echo "Invalid option: -${OPTARG} ($programName -h for help)"
+            exit 1;;
+    esac
+done
 
-echo "Parameters: -change-sink | -get-volume | -set-volume"
+usage
